# Generated by Django 5.2.4 on 2025-07-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('app_img_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('steam_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('profile_img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='backend.steamgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to='backend.steamuser')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
